name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    branches:
      - master

  pull_request:
    branches:
      - '*'

jobs:
  skippy:
    name: 'Determine if CI should be run'
    continue-on-error: true # Shouldn't stop the CI if the checker is buggy
    runs-on: ubuntu-latest
    outputs:
      # Map checkSkip output to job
      should_skip: ${{ steps.checkSkip.outputs.should_skip }}
    steps:
      - id: checkSkip
        name: Skipping check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          # Required to use path skipping.
          skip_after_successful_duplicate: 'true'
          # Paths to ignore, uses micromatch:
          # https://github.com/micromatch/micromatch
          #
          # This is a JSON array, provided as text, so no comments, sadly.
          #
          # FIXME: disabled ".github/workflows/ci.yml" to test the new logic.
          paths_ignore: |
            [
              "**.cfg",
              "**.nims",
              "**.nim",
              "**.nimble",
              "tests/**"
            ]
          # Takes a JSON array as text.
          #
          # Ignore skipping logic if the events is one of these:
          do_not_skip: |
            [
              "schedule"
            ]

  build:
    # Only build if our checker give a green light.
    needs: skippy
    if: needs.skippy.outputs.should_skip != 'true'

    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest'] #, 'ubuntu-latest']
        nim: ['devel']
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: cps

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Run examples
        shell: bash
        run: |
          cd cps
          nimble --accept develop
          cd examples
          env GITHUB_ACTIONS=false balls --path=".."

      - name: Run tests
        shell: bash
        run: |
          cd cps
          nimble --accept develop
          nimble test

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        shell: bash
        run: |
          cd cps
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --outdir:docs --path="." \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            cps.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.os == 'macos-latest' && matrix.nim == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: cps/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
